from wsd.tests.build.ngrams.ngramparsertest import NGramParserTest
from wsd.tests.build.preparation.resolvethreadtest import ResolveThreadTest
from wsd.tests.build.preparation.preparethreadtest import PrepareThreadTest 
from wsd.tests.build.wikiparser.readertest import ReaderTest
from wsd.tests.build.wikiparser.wikiparsertest import WikiParserTest
from wsd.tests.build.wikiparser.readingthreadtest import ReadingThreadTest
from wsd.tests.build.wikiparser.workingthreadtest import WorkingThreadTest
from wsd.tests.main.termidentifiertest import TermIdentifierTest
from wsd.tests.main.meaningfindertest import MeaningFinderTest 
from wsd.tests.main.commonnessretrievertest import CommonnessRetrieverTest 
from wsd.tests.main.relatednesscalculatortest import RelatednessCalculatorTest
from wsd.tests.main.decidertest import DeciderTest
from wsd.tests.main.htmloutputtertest import HTMLOutputterTest
from suite import suite