from wsd.tests.algorithm.meaningfindertest import MeaningFinderTest
from wsd.tests.algorithm.relatednessretrievertest import RelatednessRetrieverTest
from wsd.tests.algorithm.relatednesscalculatortest import RelatednessCalculatorTest
from wsd.tests.algorithm.decidertest import DeciderTest
from wsd.tests.algorithm.linkdetectortest import LinkDetectorTest
from wsd.tests.build.articleinsertertest import ArticleInserterTest
from wsd.tests.build.disambiguationinsertertest import DisambiguationInserterTest
from wsd.tests.build.ngraminsertertest import NGramInserterTest
from wsd.tests.database.mysqldatabasetest import MySQLDatabaseTest 
from wsd.tests.database.mysqlbuildviewtest import MySQLBuildViewTest
from wsd.tests.database.mysqlworkviewtest import MySQLWorkViewTest
from wsd.tests.evaluation.workviewtest import EvaluationWorkViewTest
from wsd.tests.evaluation.samplereadertest import SampleReaderTest
from wsd.tests.runner.termidentifiertest import TermIdentifierTest
from wsd.tests.runner.htmloutputtertest import HTMLOutputterTest
from wsd.tests.wikipedia.linkextractortest import LinkExtractorTest
from wsd.tests.wikipedia.ngramextractortest import NGramExtractorTest
from wsd.tests.wikipedia.wikipediareadertest import WikipediaReaderTest
from wsd.tests.wikipedia.wikipediapreprocessortest import WikipediaPreProcessorTest
from testsuite import testsuite
from e2etestsuite import e2etestsuite