from wsd.tests.algorithm.meaningfindertest import MeaningFinderTest
from wsd.tests.algorithm.relatednessretrievertest import RelatednessRetrieverTest
from wsd.tests.algorithm.relatednesscalculatortest import RelatednessCalculatorTest
from wsd.tests.algorithm.decidertest import DeciderTest
from wsd.tests.build.ngrams.ngramparsertest import NGramParserTest
from wsd.tests.build.ngrams.ngramthreadtest import NGramThreadTest
from wsd.tests.build.preparation.resolvethreadtest import ResolveThreadTest
from wsd.tests.build.preparation.preparethreadtest import PrepareThreadTest 
from wsd.tests.build.wikiparser.readertest import ReaderTest
from wsd.tests.build.wikiparser.wikiparsertest import WikiParserTest
from wsd.tests.build.wikiparser.readingthreadtest import ReadingThreadTest
from wsd.tests.build.wikiparser.workingthreadtest import WorkingThreadTest
from wsd.tests.database.mysqldatabasetest import MySQLDatabaseTest 
from wsd.tests.database.mysqlbuildviewtest import MySQLBuildViewTest
from wsd.tests.database.mysqlworkviewtest import MySQLWorkViewTest
from wsd.tests.evaluation.connectortest import EvaluationConnectorTest
from wsd.tests.evaluation.wikitermidentifiertest import WikiTermIdentifierTest
from wsd.tests.evaluation.samplereadertest import SampleReaderTest
from wsd.tests.runner.termidentifiertest import TermIdentifierTest
from wsd.tests.runner.htmloutputtertest import HTMLOutputterTest
#from wsd.tests.main.meaningfindertest import MeaningFinderTest 
#from wsd.tests.main.commonnessretrievertest import CommonnessRetrieverTest 
#from wsd.tests.main.relatednesscalculatortest import RelatednessCalculatorTest
#from wsd.tests.main.decidertest import DeciderTest
#from wsd.tests.main.htmloutputtertest import HTMLOutputterTest
from wsd.tests.wikipedia.linkextractortest import LinkExtractorTest
from wsd.tests.wikipedia.ngramextractortest import NGramExtractorTest
from wsd.tests.wikipedia.wikipediareadertest import WikipediaReaderTest
from wsd.tests.wikipedia.wikipediapreprocessortest import WikipediaPreProcessorTest
from testsuite import testsuite
from e2etestsuite import e2etestsuite